#!/bin/zsh

mkdir -p .cache
HASH=$(cat $1 logic-game.cls | md5sum | awk '{print $1}')
OUTPUT=${1%.lcg}
HASHED=.cache/$HASH

if [[ -a $HASHED.png ]]; then
    cp $HASHED.png $OUTPUT.png
    exit 0
fi

(echo '\documentclass{logic-game}\\begin{document}\\begin{tikzpicture}'; cat $1; echo '\\end{tikzpicture}\\end{document}') > /tmp/temp.tex
pdflatex -shell-escape -interaction=nonstopmode -output-directory /tmp -file-line-error /tmp/temp.tex | grep ".*:[0-9]*:.*" | sed "s\`^.*:\`$OUTPUT:\`"
pdftoppm -f 1 -singlefile -rx 1000 -ry 1000 -png /tmp/*.pdf $HASHED

exec $0 "$@"
